class HelpTopics:
    ABOUT = "About"
    AUTO_ANALYSIS = "AutoAnalysisPlugin"
    BLOCK_MODEL = "BlockModel"
    BOOKMARKS = "BookmarkPlugin"
    BYTE_VIEWER = "ByteViewerPlugin"
    CODE_BROWSER = "CodeBrowserPlugin"
    COMMENTS = "CommentsPlugin"
    DATA = "DataPlugin"
    DATA_MANAGER = "DataManagerPlugin"
    DATA_TYPE_EDITORS = "DataTypeEditors"
    DECOMPILER = "DecompilePlugin"
    DIFF = "Diff"
    EQUATES = "EquatePlugin"
    EXPORTER = "ExporterPlugin"
    FIND_REFERENCES = "LocationReferencesPlugin"
    FRONT_END = "FrontEnd"
    GLOSSARY = "Glossary"
    HIGHLIGHT = "SetHighlightPlugin"
    IMPORTER = "ImporterPlugin"
    INTRO = "Intro"
    LABEL = "LabelMgrPlugin"
    NAVIGATION = "Navigation"
    MEMORY_MAP = "MemoryMapPlugin"
    PE2XML = "PE2XMLPlugin"
    PROGRAM = "ProgramManagerPlugin"
    PROGRAM_TREE = "ProgramTreePlugin"
    REFERENCES = "ReferencesPlugin"
    RELOCATION_TABLE = "RelocationTablePlugin"
    REPOSITORY = "Repository"
    SEARCH = "Search"
    SELECTION = "Selection"
    SYMBOL_TABLE = "SymbolTablePlugin"
    SYMBOL_TREE = "SymbolTreePlugin"
    TOOL = "Tool"

# You can access the help topics like this:
print(HelpTopics.ABOUT)
