Here is the translation of the given Java code into Python:

```Python
class NotOwnerException(Exception):
    """ Exception thrown if user is not the owner of a file or data object being accessed."""
    
    def __init__(self, msg="User is not the owner"):
        super().__init__(msg)
```

Note that in Python, we don't need to explicitly define constructors like `__init__` because it's automatically generated by the class definition. Also, there are no packages or imports needed as they're handled differently in Python compared to Java.