Here is the translation of the Java code to Python:
```python
import logging

class StopTask:
    def __init__(self):
        self.application = None
        self.restore_system_props = {}

    @property
    def application(self):
        return self._application

    @application.setter
    def set_quarkus_application(self, quarkus_app):
        self._application = quarkus_app

    def stop(self):
        if not self.application:
            logging.debug("No application found.")
            return

        try:
            self.application.close()
            logging.info("Quarkus application stopped.")
        except Exception as e:
            raise RuntimeError(e)

        finally:
            self.application = None
            for k, v in self.restore_system_props.items():
                if v is not None:
                    import os
                    os.environ[k] = v
                else:
                    del os.environ[k]

if __name__ == "__main__":
    pass  # This code doesn't have a main function, so we don't need to do anything here.
```
Note that I've used the `logging` module instead of Java's equivalent logging API. Also, Python has no direct equivalent to Java's `AutoCloseable` interface, but I've implemented it as a simple property with a setter method.

Also, note that in Python, we don't need to explicitly define getters and setters for properties like we do in Java. The above code uses the `@property` decorator to create read-only properties, and the corresponding setter methods are automatically generated by Python's syntax.