class BukkitBrigadierCommandSource:
    def get_bukkit_entity(self) -> None | 'Entity':
        ...

    def get_bukkit_world(self) -> None | 'World':
        ...

    def get_bukkit_location(self) -> None | 'Location':
        ...

    def get_bukkit_sender(self) -> 'CommandSender':
        ...
