class BootImageLiveObjects:
    OOME_WHEN_THROWING_EXCEPTION = 1
    OOME_WHEN_THROWING_OOME = 2
    OOME_WHEN_HANDLING_STACK_OVERFLOW = 3
    NO_CLASS_DEF_FOUND_ERROR = 4
    CLEARED_JNI_WEAK_SENTINEL = 5

    INTRINSIC_OBJECTS_START = 6
