class TextFilterStrategy:
    CONTAINS = "CONTAINS"
    STARTS_WITH = "STARTS_WITH"
    MATCHES_EXACTLY = "MATCHES_EXACTLY"
    REGULAR_EXPRESSION = "REGULAR_EXPRESSION"

print(TextFilterStrategy.CONTAINS)
